services:
  - type: web
    name: telhan-sathi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m flask db upgrade
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: telhan-sathi-db
          property: connectionString

databases:
  - name: telhan-sathi-db
    plan: free
    databaseName: telhan_sathi
    user: telhan_user
